AllCops:
  Exclude:
    - 'spec/fixtures/**/*'
  TargetRubyVersion: 2.4
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - '**/*.gemspec'

Naming/MethodParameterName:
  MinNameLength: 1
